export default {
  SEARCH: 'SEARCH',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAIL: 'SEARCH_FAIL',
  SEARCH_TERM_CHANGED: 'SEARCH_TERM_CHANGED',
  CLEAR_SEARCH: 'CLEAR_SEARCH',
  LOAD_MORE_SUCCESS: 'LOAD_MORE_SUCCESS',
  LOAD_MORE_FAIL: 'LOAD_MORE_FAIL',
  TOP_SEARCHES_LOAD: 'TOP_SEARCHES_LOAD',
  TOP_SEARCHES_SUCCESS: 'TOP_SEARCHES_SUCCESS',
  TOP_SEARCHES_FAIL: 'TOP_SEARCHES_FAIL',
  TOGGLE_TOP_SEARCH_RESULTS_SECTION: 'TOGGLE_TOP_SEARCH_RESULTS_SECTION'
};
